services:
  proxy:
    image: nginx:stable-alpine3.19
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/templates
    restart: unless-stopped

  db:
    image: mongo:7.0.12
    environment:
      - MONGO_INITDB_ROOT_USERNAME=umcu
      - MONGO_INITDB_ROOT_PASSWORD=changeme
    expose:
      - 27017
    volumes:
      - ./mongo:/data/db
    restart: unless-stopped

  api:
    build: .
    environment:
      - SPRING_PROFILE=prod # Do not change
      - TMDB_API_KEY=
      - TMDB_LIST_ID=8289533
      - DB_USERNAME=umcu
      - DB_PASSWORD=changeme
    expose:
      - 8080
    depends_on:
      - proxy
      - db
    restart: unless-stopped

volumes:
  nginx:
  mongo:
