name: umcu-api

services:
  proxy:
    image: nginx:stable-alpine3.19
    ports:
      # The left-side port is the port that will be used for external connections, this can be changed to whatever.
      # The right-side port must match the port in "default.conf.template".
      - "8536:8536"
    volumes:
      - ./nginx:/etc/nginx/templates
    restart: unless-stopped

  mongo:
    image: mongo:7.0.12
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    expose:
      - 27017
    volumes:
      - ./mongo:/data/db
    restart: unless-stopped

  umcu_api:
    image: ghcr.io/upcomingmcu/api:0.4.0
    environment:
      - SPRING_PROFILE=prod
      - TMDB_API_KEY=${TMDB_API_KEY}
      - TMDB_LIST_ID=${TMDB_LIST_ID}
      - DB_USERNAME=${MONGO_USERNAME}
      - DB_PASSWORD=${MONGO_PASSWORD}
    expose:
      - 8080
    depends_on:
      - proxy
      - mongo
    restart: unless-stopped

volumes:
  nginx:
  mongo:
